# Generated by Django 3.2.9 on 2022-01-18 14:51

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('currency', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=25)),
                ('status', models.BooleanField(default=True, help_text='Designates whether this company should be treated as active. Unselect this instead of deleting companies.', verbose_name='active')),
                ('image', models.ImageField(default='users/default.png', upload_to=company.models.upload_to, verbose_name='image')),
            ],
        ),
    ]
