# Generated by Django 3.2.9 on 2022-03-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220314_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
    ]
