# Generated by Django 3.2.9 on 2022-03-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='code',
            new_name='id',
        ),
    ]
