# Generated by Django 3.2.9 on 2022-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('company', '0012_alter_company_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.User'),
        ),
    ]
