# Generated by Django 3.2.9 on 2022-03-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('company', '0013_alter_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='authentication.user'),
        ),
    ]
