# Generated by Django 3.2.9 on 2022-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
    ]
