# Generated by Django 3.2.9 on 2022-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('company', '0015_auto_20220318_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.User'),
        ),
    ]
