# Generated by Django 3.2.9 on 2022-03-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('company', '0016_auto_20220318_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
