# Generated by Django 3.2.9 on 2021-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginattempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattemtps',
            name='currencycode',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='loginattemtps',
            name='currencyname',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='loginattemtps',
            name='currencysymbol',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
